version: '3.8'
services:
  postgres:
    image: postgres:16.3-alpine
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  flyway:
    enabled: true
    user: postgres
    password: postgres
    schema: productdb
    locations:
      - classpath:db/dev/migration
volumes:
  postgres_data:
