spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/productdb
    username: root
    password: password
  flyway:
    url: jdbc:postgresql://localhost:5432/productdb
    user: root
    password: password


logging:
  level:
    org.springframework.r2dbc.core: DEBUG
