spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/productdb
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    enabled: true
    url: ${SPRING_FLYWAY_URL}
    user: ${SPRING_FLYWAY_USER}
    password: ${SPRING_FLYWAY_PASSWORD}
    schemas: productdb
    locations: classpath:db/dev/migration
  data:
    r2dbc:
      repositories:
        enabled: true

logging:
  level:
    org.springframework.r2dbc.core: DEBUG
    org.flywaydb: DEBUG
