spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-service-group
      auto-offset-reset: earliest
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: pricing.update
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/productdb
    username: postgres
    password: password
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/productdb
    user: postgres
    password: password
    schemas: productdb
    clean-disabled: false
    locations:
      - classpath:db/dev/migration
  data:
    r2dbc:
      repositories:
        enabled: true

logging:
  level:
    org.springframework.r2dbc.core: DEBUG
