spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/productdb
    username: postgres
    password: password
  flyway:
    enabled: true
    url: jdbc:postgresql://postgres:5432/productdb
    user: postgres
    password: password
    schemas: public
    locations:
      - classpath:db/migration

logging:
  level:
    org.springframework.r2dbc: DEBUG