spring:
  flyway:
    enabled: true
    locations: classpath:db/migration,classpath:db/prod/testmigration
    clean-disabled: false  # Habilita la operación de limpieza para pruebas
    schemas: productdb
    default-schema: productdb

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: TRACE